# Generated by Django 5.2.4 on 2025-10-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdefinition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
