# Generated by Django 5.2.4 on 2025-11-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarshipprogram',
            old_name='criteria',
            new_name='criteria1',
        ),
        migrations.AddField(
            model_name='scholarshipprogram',
            name='criteria2',
            field=models.TextField(blank=True),
        ),
    ]
