# Generated by Django 5.2.4 on 2025-10-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_reportdefinition_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='shared_with_uuids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
